### ISSUE TITLE
Add a CLI flag to support a timeout

### ISSUE THREAD

**Issue by johncblandii** [kayac/ecspresso#598]
In order to automate this through our CD process, we need to define a timeout through a CLI flag and not through editing a file.

If there isn't a way to handle this, please add a flag to handle this. If there is a way, I'd love to know it. 😄

**Comment by fujiwara** [comment]
A configuration file of ecspresso is parsed as a template.
So you can set timeout by the `TIMEOUT` environment variable like the following example.

```yaml
# ecspresso.yml
timeout: '{{ env `TIMEOUT` `10m` }}'
```

**Comment by johncblandii** [comment]
In CI, we call `init`, `jq` some task def changes, then call `deploy`. We don't have `yq` installed to edit the config.

This is why a default way would be better instead of us doing manual changes to configs in an automated scenario.

**Comment by fujiwara** [comment]
ecspresso supposes a typical use case as below,
1. Run `ecspresso init` manually. Create configuration/definition files.
2. Modify these files to templates manually and commit to a CI repository.
3. CI checkouts these files and runs `ecspresso deploy` with environment variables (defined by runtime).

I did not assume to modify definition files by jq or other tools.

I added typical use case into readme. https://github.com/kayac/ecspresso/pull/600

**Comment by fujiwara** [comment]
@johncblandii ecspresso's configuration file includes various elements (that are fixed by the environment, or are flexible by runtime).

This situation is confusing, but adding the `--timeout` flag makes more confusion.

So, I tried to omit the `timeout` element in a configuration file created by `ecspresso init` command at #602.

This fix became `ecspresso init` does not write `timeout`. Therefore you can add any `timeout: "xxx"` to the configuration file.

How about #602?

**Comment by johncblandii** [comment]
I'm fine with it being omitted, but let us supply one so we can control it in our CI/CD process without having to manipulate a file.

This is a very common CLI request. Just give us control over settings.

**Comment by fujiwara** [comment]
@johncblandii ecspresso v2 adds `--timeout` cli flag. try it!
